# Generated by Django 4.2.9 on 2024-01-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0010_unit_trans_unit_pending"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwaVerification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=32)),
                ("remote_url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="trans_owave_token_563265_idx")
                ],
            },
        ),
    ]
